### ISSUE TITLE
Missing mkdir ./dist

### ISSUE THREAD

**Issue by aous72** [chafey/kakadujs#1]
Hi Chris,

While using build-wasm.sh, the generated files were copied to a file called "./dist"
I think you need to create the folder "dist" before copying files to it.

That is, before
```cp ./build-wasm/src/kakadujs.js ./dist```
put 
```mkdir -p ./dist```
or you may have a better approach.

Cheers,
Aous.

**Comment by chafey** [comment]
Fixed, thanks for the bug report!
